name: CI & GitHub Pages Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Turborepo Build
        run: npx turbo run build

      - name: Prepare Deployment Directory
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p deploy_dist
          cp -r app/host/dist/* deploy_dist/
          mkdir -p deploy_dist/feature-a
          cp -r app/feature-a/dist/* deploy_dist/feature-a/
          mkdir -p deploy_dist/feature-b
          cp -r app/feature-b/dist/* deploy_dist/feature-b/

      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "deploy_dist"

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
